@url = https://stunning-space-dollop-gg49qv5x4752vrj4-8080.app.github.dev/filmes

POST {{url}}
Content-Type: application/json

{
    "titulo": "Star wars",
    "idGenero": 1,
    "idsProdutoras": [1,2]
}

###
GET {{url}}

###
PUT {{url}}/3
Content-Type: application/json

{
    "titulo": "Star wars, A vingança dos Sith",
    "idGenero": 2,
    "idsProdutoras": [2]
}

###
DELETE {{url}}/2

###
GET {{url}}/2+