@url = https://stunning-space-dollop-gg49qv5x4752vrj4-8080.app.github.dev/genero

POST {{url}}
Content-Type: application/json

{
    "nome": "Acao"
}

###
GET {{url}}

###
PUT {{url}}/3
Content-Type: application/json

{
    "nome": "Comedia"
}

###
DELETE {{url}}/4

###
GET {{url}}/2